[Updated] checking if the transfer was successfully

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,28 @@
 #!/usr/bin/env bash
-# This script enables file transfer from our client to a server.
-# It requires 4 parameters:
-#  1: The file's path to be transferred
-#  2: The IP address of the destination server
-#  3: The username for the scp connection
-#  4: The path to the SSH private key used by scp
+# checking for command line arguments
 
 if [ $# -lt 4 ]
 then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+ 	 echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+ 	 exit 1
+fi
+
+# assigning parameters to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# disabling strict host key checking
+
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@ip:~/"
+
+
+#checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "FILE WAS TRANSFERED SUCCESSFULLY"
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+	echo "FILE TRANSFER FAILED"
 fi
